{
    "experiment_run": 1,
    "gpu": "1",
    "model_name": "lexnet", 
    "dataset": "dataset_name",
    "validation_split": [5,1],
    "epochs": 1000,
    "warm_epochs": 5,
    "push_freq": 20,
    "push_start": 10,
    "push_last_epochs": 20,
    "batch_size": 1024,
    "base_architecture": "lexnet_backbone", 
    "base_architecture_last_filters": 32,
    "prototypes": 1,
    "prototype_size": [1,1],
    "baseline_activation_function": "sigmoid",
    "prototype_activation_function": "log",
    "lrs":{"features": 1e-3, "add_on_layers": 1e-1, "prototype_vectors": 1e-1, "last_layer_optimizer_lr": 1e-2},
    "joint_lr_step_size": 100,
    "gamma_lr": 0.5,
    "coefs_list": {"crs_ent": 1, "clst": 0.8, "sep": -0.08, "reg_protos": 1e-3, "reg_last": 1e-4},
}